from .dashboard import dashboard_view
from .analytics import analytics_view
from .availability import availability_view
from .clients import *
from .assets import *
from .deals import *
from .contracts import *
from .payments import *
from .tasks import *