# Generated by Django 5.0 on 2025-07-11 19:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('color', models.CharField(default='#6c757d', max_length=7, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$', 'Неверный формат цвета')], verbose_name='Цвет (HEX)')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'Рекламный актив', 'verbose_name_plural': 'Рекламные активы'},
        ),
        migrations.AlterModelOptions(
            name='availabilityslot',
            options={'verbose_name': 'Слот доступности', 'verbose_name_plural': 'Слоты доступности'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-start_date'], 'permissions': [('can_upload_contract', 'Может загружать скан договора')], 'verbose_name': 'Договор', 'verbose_name_plural': 'Договоры'},
        ),
        migrations.AlterModelOptions(
            name='deal',
            options={'permissions': [('can_change_deal_status', 'Может изменять статус сделки')], 'verbose_name': 'Сделка', 'verbose_name_plural': 'Сделки'},
        ),
        migrations.AlterModelOptions(
            name='dealtask',
            options={'ordering': ['-due_date'], 'permissions': [('can_reassign_task', 'Может переназначать задачи')], 'verbose_name': 'Задача по сделке', 'verbose_name_plural': 'Задачи по сделкам'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date'], 'permissions': [('can_confirm_payment', 'Может подтверждать платежи')], 'verbose_name': 'Платёж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='client',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер'),
        ),
        migrations.AddField(
            model_name='contract',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/%d/', verbose_name='Скан договора'),
        ),
        migrations.AddField(
            model_name='contractasset',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipts/%Y/%m/%d/', verbose_name='Квитанция'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('bus', 'Автобус'), ('bus_stop', 'Остановка'), ('screen', 'Медиаэкран'), ('billboard', 'Билборд')], max_length=20, verbose_name='Тип актива'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Дневная ставка'),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='dealtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Банковский перевод'), ('other', 'Другое')], max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('completed', 'Завершён'), ('failed', 'Неудачный'), ('refunded', 'Возвращён')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_active'], name='core_client_is_acti_f1c166_idx'),
        ),
        migrations.AddIndex(
            model_name='dealtask',
            index=models.Index(fields=['assigned_to'], name='core_dealta_assigne_e19b6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('name', 'contact_person'), name='unique_client_contact'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='assets', to='core.tag', verbose_name='Теги'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(check=models.Q(('daily_rate__gte', 0)), name='daily_rate_positive'),
        ),
    ]
