# Generated by Django 5.0 on 2025-06-24 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilityslot',
            options={'verbose_name': 'Слот доступности', 'verbose_name_plural': 'Слоты доступности'},
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='amount',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='availabilityslot',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Свободен'),
        ),
        migrations.AddField(
            model_name='contract',
            name='deal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='core.deal', verbose_name='Сделка'),
        ),
        migrations.AddField(
            model_name='contract',
            name='number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подписания'),
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='end_date',
            field=models.DateField(verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='start_date',
            field=models.DateField(verbose_name='Начало'),
        ),
    ]
